thread:
	g++ -pthread -o thread -std=c++11 thread.cpp
future:
	g++ -pthread -o future -std=c++11 future.cpp
atomic:
	g++ -o atomic -std=c++11 atomic.cpp
test:
	g++ -o test -std=c++11 test.cpp
clean:
	rm thread future atomic test
